dhex:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Position Controllers ---------------------------------------
  right_wheel_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: dhex_base_link_TO_right_wheel
    pid: {p: 0.01, i: 0.00001, d: 0.00001, i_clamp: 0.05, antiwindup: true}
  left_wheel_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: dhex_base_link_TO_left_wheel
    pid: {p: 0.01, i: 0.00001, d: 0.00001, i_clamp: 0.05, antiwindup: true}