# Publish all joint states -----------------------------------
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

# Position Controllers ---------------------------------------
joint1_position_controller:
  type: position_controllers/JointPositionController
  joint: M1_TO_LINK0
  pid: {p: 1.0, i: 1, d: 1.0}
joint2_position_controller:
  type: position_controllers/JointPositionController
  joint: M2_TO_LINK1
  pid: {p: 1.0, i: 1, d: 1.0}
joint3_position_controller:
  type: position_controllers/JointPositionController
  joint: M4_TO_LINK2
  pid: {p: 1.0, i: 1, d: 1.0}
joint4_position_controller:
  type: position_controllers/JointPositionController
  joint: M5_TO_LINK3
  pid: {p: 1.0, i: 1, d: 1.0}
joint5_position_controller:
  type: position_controllers/JointPositionController
  joint: M6_TO_LINK4
  pid: {p: 1.0, i: 1, d: 1.0}
