joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

right_velocity_controller:
  type: effort_controllers/JointVelocityController
  joint: dhex_base_link_TO_right_wheel
  pid: { p: 5, d: 1, i: 1}

left_velocity_controller:
  type: effort_controllers/JointVelocityController
  joint: dhex_base_link_TO_left_wheel
  pid: { p: 5, d: 1, i: 1}      


    
state_publish_rate: 25    