footprint: [[-0.12, -0.11], [-0.12, 0.11], [0.12, 0.11], [0.12, -0.11]]
footprint_padding: 0.01

robot_base_frame: base_link
update_frequency: 4.0
publish_frequency: 3.0
transform_tolerance: 0.5

resolution: 0.05

obstacle_range: 1
raytrace_range: 2

static:
    map_topic: /map
    subscribe_to_updates: true

inflation:
    inflation_radius: 0.45